### ISSUE TITLE
Announcing the First Hub Champion Training Workshop page for website

### ISSUE THREAD

**Issue by jnywong** [czi-catalystproject/website#10]
This issue tracks the drafting, review and approval of the _Announcing the First Hub Champion Training Workshop_ page  for the Catalyst website.

This issue is complete when: the copy of this page is approved and can be moved to GitHub ready for publishing on the website (at that point we need to move the copy into the code of this repo on GitHub).

Google doc for drafting copy: https://docs.google.com/document/d/1obfcSi0adapwlWarIjp-Sw-OnGrgKDAVV1-Uch3V8ck/edit?usp=sharing

**Roles**
Drafting content: @katiepratt and @Tajuddeen1
Initial review: @LouWoodley
Coordination / project management: @Tajuddeen1
Review: corresponding project sub-teams
Handoff - @katiepratt hands off to @jnywong to prep for website publishing

- [x] Draft initial page content @jnywong 
- [x] Sub-teams for review @tobyhodges 
- [x] Address edits / suggestions @jnywong 
- [x] Final signoff @katiepratt 
- [x] Handoff to Jenny @katiepratt 
- [x] Publish on website @jnywong

**Comment by jnywong** [comment]
Waiting to finalise the dates of the training event before handing off to @katiepratt  :)

**Comment by jnywong** [comment]
Hey @katiepratt , I have finalised this draft – could you check for sign-off please? Cheers.

**Comment by katiepratt** [comment]
Hi Jenny - this looks fine for the most part (although I'd like to confirm a couple of style standards for the website - e.g., how we describe dates and times). I think we would want at least some of the rest of the website to be up as well, when this announcement is posted, and we're making good progress towards updated copy for the Home, About, and Training pages. Are you available to join Lou, Taj and I on our Zoom call? It's at 10am EDT / 2pm GMT tomorrow (Thursday, 21 March). That way we can just talk through some of these interdependencies and hopefully get something stood up by the end of the week.

**Comment by jnywong** [comment]
Thanks @katiepratt ! Yes I can join the call later day to iron out some details, see you soon

**Comment by jnywong** [comment]
Closed by commit https://github.com/czi-catalystproject/website/commit/5b5521bdeed2dffbb166473d8c073799df033bee

I have archived the Google Doc and created a new working copy in our team folder.

If you would like to raise further changes, please create a new issue.
